server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
         uri: https://github.com/justdoplzz/msa-config-repo   #Github Repository 주소
         